[project]
name = 'Prediction-Market-for-Climate-Change-Mitigation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.climate-prediction-nft]
path = 'contracts/climate-prediction-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.market-registry]
path = 'contracts/market-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
